### ISSUE TITLE
Random crashes on game start

### ISSUE THREAD

**Issue by hedger** [bolknote/Flipper-Zero-Hangman-Game#3]
I'm using current version from Flipper app catalog on latest firmware, 94.1.

When starting a new game and after selecting language (usually on English), it randomly crashes Flipper with NULL pointer dereference.

**Comment by bolknote** [comment]
Thanks for the issue!

Could you provide a little more information? Does this happen on the first launch? Or after you have won or lost? Do you have official firmware or custom?

**Comment by bolknote** [comment]
If possible, try to run this debug build. Maybe I can find out where crashes are happening.

[hangman_d.elf.zip](https://github.com/bolknote/Flipper-Zero-Hangman-Game/files/13309495/hangman_d.elf.zip)

**Comment by hedger** [comment]
<img width="984" alt="image" src="https://github.com/bolknote/Flipper-Zero-Hangman-Game/assets/277532/9ceaa7b1-d652-4030-af8b-03134d30015c">

app->lang is NULL. There's a race between render callback and game state init.

**Comment by bolknote** [comment]
Oh, yes, IC! Big thanks!
