### ISSUE TITLE
App not building on toolchain 46.0 f7

### ISSUE THREAD

**Issue by doomwastaken** [bolknote/Flipper-Zero-Hangman-Game#5]
Greetings! I am from Flipper Devices team and would like to say thank you for submitting your app to the catalog. We are finalizing API prior to 1.0 release and currently your application cannot be built for latest toolchain. Currently we are testing 0.95.0-rc and app is not being built for that version. 

We are currently working on automating the messages from our build server, so this one is manual :)

If you have any questions, just tag me

**Comment by bolknote** [comment]
Hi, @doomwastaken! Thank you very much! Could you tell me what problems occur and how do I install this RC version?

**Comment by doomwastaken** [comment]
Just try to compile your app on latest release candidate in firmware or try validating it with latest version of ufbt, whichever way you prefer

**Comment by doomwastaken** [comment]
Sadly the logs are not available for failed builds, so I cannot pull them out (this should be fixed later today, we are releasing new backend version for catalog).  I can only see a part of a log saved, there is a compiler warning, we are treating them as errors. Only ignoring linter warnings. So, hopefully, there won't be any difficulties. Attached all that I have available
![image](https://github.com/bolknote/Flipper-Zero-Hangman-Game/assets/72250702/11c09bec-9271-4442-8857-54352a611692)

**Comment by bolknote** [comment]
The latest version of ufbt builds my code:

```
$ python3 -m pip install --upgrade ufbt
Requirement already satisfied: ufbt in /usr/local/lib/python3.11/site-packages (0.2.4.3)

$ ufbt
scons: Entering directory /Users/bolk/.ufbt/current/scripts/ufbt
	INSTALL	/Users/bolk/Projects/Flipper/Hangman/dist/hangman.fap
	INSTALL	/Users/bolk/Projects/Flipper/Hangman/dist/debug/hangman_d.elf
	CDB	/Users/bolk/Projects/Flipper/Hangman/.vscode/compile_commands.json
	APPCHK	/Users/bolk/.ufbt/build/hangman.fap
		Target: 7, API: 39.2
```

Unfortunately, I don't know yet how to install RC. I'm still newbie. Maybe the recipe is described somewhere?

**Comment by doomwastaken** [comment]
Yeah, that is building the app. However you can validate your entire catalog submission via this guide https://github.com/flipperdevices/flipper-application-catalog/blob/main/documentation/Contributing.md#validating-manifest

you need the bottom part

**Comment by doomwastaken** [comment]
You can try following:
`ufbt update -c rc; ufbt`

This should use SDK from release candidate

**Comment by doomwastaken** [comment]
Oh guess there was unused API, nice that it wasn't something massive. In order for changes to take affect you will also need to bump version and open pull request to catalog with fresh version/commit SHA

Thank you!

**Comment by bolknote** [comment]
BTW,  I would like to ask, is it possible to push patches somehow into the firmware to make utf-8 support in the IO API in the Flipper Zero?

**Comment by doomwastaken** [comment]
I will ask on Monday, I am from QA team :) will get back to you
