### ISSUE TITLE
Typo - 'lose'

### ISSUE THREAD

**Issue by Solathian** [bolknote/Flipper-Zero-Hangman-Game#8]
Both the code and the display message in case of losing has 'lose' mistyped.
free((*app)->lang->message_loose);
"You loose"

It is 'lose'

See:

The word lose is a verb that can mean either (1) fail to win, (2) be unable find, or (3) stop having or owning something. 
The word loose is an adjective that means not tight or not strict. 
The rules for swimming at the beach are pretty loose, but I don't want to lose sight of the shoreline.
https://www.grammarly.com/blog/loose-lose/

**Comment by bolknote** [comment]
Oh, IC! Thank you!
