### ISSUE TITLE
.bolk file help

### ISSUE THREAD

**Issue by G-Edosaurus** [bolknote/Flipper-Zero-Hangman-Game#9]
I would like to contribute to this cool app by adding italian.
I have already the `.dict` file for this language, but I don't know how to make a `.bolk` file.
Could you give me some hints on how to do this?

**Comment by bolknote** [comment]
Hello!

Some time ago, I wrote this letter for a person who wanted to add the Croatian language. I hope this helps. If not, please feel free to ask questions.

-------------------

Everything went well. Did you manage to add a dictionary? You can read Russian and Tatar dictionaries like this:

with open('files_src/russian.ucs2.dict', 'rb') as file: print(file.read().decode('utf-16be'))

with open('files_src/tatar.ucs2.dict', 'rb') as file: print(file.read().decode('utf-16be'))

UTF-16 is not exactly the same as UCS-2, but the encodings are quite close.

In the dictionary file, you need to write the necessary words in UTF-8 encoding in upper case using a line feed, like this:
JABUKA
MLIJEKO
ŽELJEZNICA
And so forth.

After that, you need to convert the text from UTF-8 to UCS-2BE. I'm doing it well the well-known iconv utility:
iconv -f utf8 -t ucs-2be сroatian.utf8.dict > files/сroatian.dict

In the сroatian.bolk file needs to specify the following:
1) the name of the dictionary file (croatian.dict)
2) the number of characters in the keyboard per line
3) the number of characters in the keyboard in the column
4) minus sign («-», this is a special field to show how to store a dictionary more economically, but it's better to put a minus here and not bother)
5) character codes of the Croatian alphabet in UTF-8 encoding: 41 42 43 10C…
6) "OK" in Croatian
7) "You won!" in Croatian
8) "You lose!" in Croatian

The last step is to add Croatian to the file menu.txt I think everything is clear there: you need to add the name of the language and the name of the bolk file.

If everything doesn't work after that, send me what happened, I'll try to figure out what's wrong.

**Comment by G-Edosaurus** [comment]
Thank you very much! By following the instructions I managed to make `.bolk` file and add a language.
